# numpy函数练习

### 1. np.prod()

In [57]:
import numpy as np
x = np.array([1,2,3,4])     
np.prod(x)               # 计算所有元素的乘积

24

In [33]:
a = np.array([[2,3],[5,6]])
print(np.prod(a, axis=1))       # 按列处理，每行的元素相乘
print(np.prod(a, axis=0))       # 按行处理，每列的元素相乘

[ 6 30]
[10 18]


In [40]:
b = np.arange(4)
b.shape
b.reshape(*a.shape)
# np.prod(a)

array([[0, 1],
       [2, 3]])

### 2. python动态创建变量名

In [64]:
names = locals()
# names = globals()
for i in range(3):
    names['w%d'%i] = i*2
print(w0, w1,w2)

0 2 4


In [70]:
name = {}
for i in range(3):
    name['w'+str(i)] = 233
name

{'w0': 233, 'w1': 233, 'w2': 233}

In [2]:
a = np.ones((2,3))
a*np.array([1,2,3]) + np.ones((3))

array([[2., 3., 4.],
       [2., 3., 4.]])

In [6]:
a = np.array([1,2,3])
np.tile(a, (2,1))

array([[1, 2, 3],
       [1, 2, 3]])

In [22]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

### 3. numpy的pad功能

In [40]:
a = np.zeros((2,2))
np.pad(a, ((2,1),(2,1)), 'constant', constant_values=((-1,2),(3,4)))

array([[ 3.,  3., -1., -1.,  4.],
       [ 3.,  3., -1., -1.,  4.],
       [ 3.,  3.,  0.,  0.,  4.],
       [ 3.,  3.,  0.,  0.,  4.],
       [ 3.,  3.,  2.,  2.,  4.]])

In [66]:
a = [1]*12
a = np.array(a).reshape(3,2,2)
print(a)
np.pad(a, ((0,),(2,),(2,)), 'constant', constant_values=0)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0],
        [0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0],
        [0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0],
        [0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [56]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [107]:
a = np.arange(12).reshape(1, 2,3,2)
a[0,0,2,0] = 20
print(a)
print(np.max(a, axis=3))
b = np.argmax(a, axis=3)
b.shape

[[[[ 0  1]
   [ 2  3]
   [20  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]]
[[[ 1  3 20]
  [ 7  9 11]]]


(1, 2, 3)

### 4. unravel_index还原argmax在矩阵中的索引

In [119]:
a= np.array([[2,6],[0,7]])
print(a)
print(np.max(a))
print(np.where(a == np.max(a)))
np.argmax(a)

[[2 6]
 [0 7]]
7
(array([1], dtype=int64), array([1], dtype=int64))


3

In [123]:
ind = np.unravel_index(np.argmax(a, axis=None), a.shape)
print(ind)
print(a[ind])

(1, 1)
7
