# numpy函数练习

### 1. np.prod()

In [1]:
import numpy as np
x = np.array([1,2,3,4])     
np.prod(x)               # 计算所有元素的乘积

24

In [33]:
a = np.array([[2,3],[5,6]])
print(np.prod(a, axis=1))       # 按列处理，每行的元素相乘
print(np.prod(a, axis=0))       # 按行处理，每列的元素相乘

[ 6 30]
[10 18]


In [40]:
b = np.arange(4)
b.shape
b.reshape(*a.shape)
# np.prod(a)

array([[0, 1],
       [2, 3]])

### 2.python动态创建变量名

In [64]:
names = locals()
# names = globals()
for i in range(3):
    names['w%d'%i] = i*2
print(w0, w1,w2)

0 2 4


In [70]:
name = {}
for i in range(3):
    name['w'+str(i)] = 233
name

{'w0': 233, 'w1': 233, 'w2': 233}

In [2]:
a = np.ones((2,3))
a*np.array([1,2,3]) + np.ones((3))

array([[2., 3., 4.],
       [2., 3., 4.]])

In [6]:
a = np.array([1,2,3])
np.tile(a, (2,1))

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
a = np.ones((1,2))
a.shape

(1, 2)

In [20]:
*a.shape

SyntaxError: can't use starred expression here (<ipython-input-20-bc8d7e1a52a5>, line 1)