# numpy的函数实例练习

### 1.np.random.choice(a, size=None, replace=True, p=None)

In [112]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
out = np.random.choice(a, 4, replace=False) # 4表示采样几个值，replace为True可以出现重复，a可以是列表或整数
out

array([7, 1, 3, 3])

In [167]:
np.random.randint(0,10,4)     # [0,10)内随机采样4个数，可以重复 与np.random.choice(10,4)相同

array([ 5, 10,  5,  9])

In [177]:
np.random.choice(5, 3, replace=False, p=[0.1, 0, 0.3, 0.6, 0])  # 安装概率p抽样，不重复

array([3, 2, 0])

### 2. np.argsort

In [183]:
a = np.array([2,3,4,1,2,6,7,8,9,0,4])
print('1.元素的排序:', np.sort(a))
print('2.元素排序的序号:', np.argsort(a))

1.元素的排序: [0 1 2 2 3 4 4 6 7 8 9]
2.元素排序的序号: [ 9  3  0  4  1  2 10  5  6  7  8]


In [188]:
a = np.array([2,3,4,1,2,6,7,8,9,0,4])
list(a[np.array([0,0,1,1,2])])

[2, 2, 3, 3, 4]

### 3. Counter 

In [366]:
from collections import Counter,OrderedDict
a = np.array([1,1,1,1,2,3,4,4,4,5])
b = [2,3,4,4,4,4,4,4,4,4,5]
count = Counter(b)         # 统计数据出现的频率，numpy的array和list都行
print(count)
print(count.most_common(1), count.most_common(1)[0][0])   # 获取票数最高的值

Counter({4: 8, 2: 1, 3: 1, 5: 1})
[(4, 8)] 4


### 4. np.bincount

In [376]:
a = [0,2,2,2,3,1,1,7,6]   # 先看最大值为7
b = np.bincount(a)
print('各个索引出现的次数:', b)          # 结果对应索引0->7
print('出现最多次的索引:', np.argmax(b)) # 如果最大次数有多个，选索引低的输出

各个索引出现的次数: [1 2 3 1 0 0 1 1]
出现最多次的索引: 2


3