# 函数练习

In [1]:
import numpy as np
import torch 

In [2]:
a = np.linspace(-10, 10, 5)          # 等差数列采样
a

array([-10.,  -5.,   0.,   5.,  10.])

In [22]:
a = np.arange(9).reshape(3,3)
b = np.arange(3)
c = np.add(a,b)

In [25]:
?np.add.at

In [15]:
a

[1, 2]

## 1. numpy.add.at

In [29]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2])
np.add.at(a, [0, 1], b)   # 在第0和1位置叠加b中对应的元素
a                         # 在a自身上加

array([2, 4, 3, 4])

In [30]:
a = np.array([1, 2, 3, 4])
np.add.at(a, [0, 1, 2, 2], 1)     # 在第0,1,2,2位置分别加1，第2个位置加了两次1
a

array([2, 3, 5, 4])

In [31]:
a = np.array([1, 2, 3, 4])
np.negative.at(a, [0, 1])       # 第0和1位置取负
a

array([-1, -2,  3,  4])

In [52]:
a = np.arange(9).reshape(3,3)
print(a)
b = np.array([1,1,1])
np.add.at(a,[0,1,0],b)
a

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## 2.numpy数组与列表切片索引不会溢出

In [91]:
a = np.arange(9)
print(a)
print(a[3:20])           # 即使end=20超过索引范围，直接返回已有数据，不会报错
b = a[20:30]             # 如果切片索引无效，返回空数组

[0 1 2 3 4 5 6 7 8]
[3 4 5 6 7 8]


In [106]:
l = [1,2,3,4,5,6]
print(l[2:20])                  # 列表也不会出现切片索引溢出问题
print(l[20:30])                 # 如果切片索引无效，返回空列表

[3, 4, 5, 6]
[]


## 3. array[None]在增加一个一维的第0维度

In [6]:
a = np.arange(9).reshape((3,3))
print(a.shape)
a

(3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
print(a[None].shape)
a[None]                     # 在最开始增加了一个维度，该维度为1

(1, 3, 3)


array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

## 4.torch定义变量类型 type_as方法

In [24]:
tensor1 = torch.tensor([1,2,3], dtype=torch.float64)
print(tensor1.type(), tensor1)
tensor2 = torch.tensor([1.1,2.2]).type_as(tensor1)   # 默认float，但type_as会使用tensor1相同的类型
print(tensor2.type(), tensor2)

torch.DoubleTensor tensor([1., 2., 3.], dtype=torch.float64)
torch.FloatTensor tensor([1.1000, 2.2000])


In [35]:
tensor1 = torch.tensor([[-1,2,3],[-2,5,0]])
print(tensor1, tensor1.shape)
print(torch.abs(tensor1))
print(torch.max(tensor1, dim=1))

tensor([[-1,  2,  3],
        [-2,  5,  0]]) torch.Size([2, 3])
tensor([[1, 2, 3],
        [2, 5, 0]])
(tensor([3, 5]), tensor([2, 1]))


## 5.PyTorch中matmul多维数组的矩阵乘积(numpy也有该函数)

In [95]:
a = torch.rand((2,3,4))         # (N,H,W) 
b = torch.rand((2,4,3))         # (N,W,H)
c = a.matmul(b)                 # matmul多维的矩阵乘积 批量矩阵乘积 (N,H,H) 
print(c.shape)
c

torch.Size([2, 3, 3])


tensor([[[1.0857, 0.9276, 0.9489],
         [1.1151, 0.8544, 0.6473],
         [0.6746, 0.4827, 0.3723]],

        [[0.6092, 0.7565, 0.8553],
         [0.6252, 1.0438, 0.7623],
         [1.1651, 1.6631, 1.9378]]])

In [100]:
a = torch.rand((1,2,3,4))            # (N,H,W) 
b = torch.rand((1,2,3,4))            # (N,W,H)
c = a.matmul(b.permute(0,1,3,2))     # permute交换坐标轴，可同时换多个 (N,H,H) 
print(c.shape)
c

torch.Size([1, 2, 3, 3])


tensor([[[[1.1186, 0.6705, 0.9549],
          [1.3065, 0.5903, 0.9391],
          [1.2467, 0.5384, 0.9302]],

         [[1.3541, 0.9563, 1.2770],
          [1.9333, 0.8833, 1.5378],
          [1.1064, 0.3854, 0.8678]]]])

## 6.numpy ceil向上取整

In [105]:
a = np.array([-1.2,-2.3,-0.5,0,1.2,3.4])
np.ceil(a)               # 向上取整

array([-1., -2., -0.,  0.,  2.,  4.])

In [130]:
it = iter(range(1,10))          # 创建一个迭代器
for i in it:
    print(i, end=' ')

1 2 3 4 5 6 7 8 9 

In [ ]:
a = torch.tensor([1]*5)
a

In [46]:
a = torch.ones((2,3) )
b = torch.ones((2,3))*2
b

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [48]:
torch.sum(a.mul(b))

tensor(12.)

In [50]:
b**2

tensor([[4., 4., 4.],
        [4., 4., 4.]])

In [57]:
a = torch.rand((2,4))
b = torch.rand((4,3))
a.mm(b)

tensor([[1.1903, 1.1325, 0.8145],
        [0.4886, 0.8139, 0.5970]])

In [84]:
print(a) 
a.t()

tensor([[-7.3873, -7.3518, -7.2636, -7.9005],
        [-7.6141, -7.9448, -7.5144, -7.8211]])


tensor([[-7.3873, -7.6141],
        [-7.3518, -7.9448],
        [-7.2636, -7.5144],
        [-7.9005, -7.8211]])

In [85]:
a.sub_(1)
a

tensor([[-8.3873, -8.3518, -8.2636, -8.9005],
        [-8.6141, -8.9448, -8.5144, -8.8211]])

In [102]:
b = a.clone()
b

tensor([[[[0.2570, 0.5183, 0.5469, 0.4554],
          [0.2139, 0.8243, 0.4869, 0.1604],
          [0.4762, 0.7017, 0.5138, 0.0362]],

         [[0.4944, 0.2622, 0.7662, 0.7043],
          [0.3446, 0.9476, 0.4081, 0.9453],
          [0.0331, 0.5100, 0.5556, 0.3637]]]])

In [140]:
import torch.nn as nn
?nn.LeakyReLU